### ISSUE TITLE
Generate repeating lines

### ISSUE THREAD

**Issue by PongLyon** [KjellMorgenstern/rbclipper#1]
[difference_test_points.txt](https://github.com/KjellMorgenstern/rbclipper/files/9009051/difference_test_points.txt)

![image](https://user-images.githubusercontent.com/28981861/176398617-c5d9655b-30dd-4a93-b75f-1114f2790186.png)

**Comment by KjellMorgenstern** [comment]
@PongLyon you might want to add a comment or open that upstream. I did not use this project since a long time.

**Comment by PongLyon** [comment]
Thank you for your reply.My test data is placed in the above TXT file, and the return result of calling the function difference is as above. The correct result should be two separate polygons

**Comment by PongLyon** [comment]
Is anyone in this situation

**Comment by PongLyon** [comment]
Is anyone in this situation

**Comment by PongLyon** [comment]
Is anyone in this situation
